services:
  postgres:
    image: postgres:16
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    env_file:
      - .env.prod
    restart: always
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis
    env_file:
      - .env.prod
    restart: always
    volumes:
      - redis-data:/data

  app:
    image: asalavei/cloud-file-storage
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
      minio:
        condition: service_started
    restart: always
    ports:
      - "80:8080"

volumes:
  postgres-data:
  minio-data:
  redis-data: