services:
  db:
    container_name: cloud-file-storage-db
    image: postgres:16-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "4777:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  minio:
    container_name: cloud-file-storage-minio
    image: minio/minio
    env_file:
      - .env
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
