spring:
  profiles:
    active: default
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4777/cloud_file_storage
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: user-files
  url: http://localhost:9000

server:
  tomcat:
    max-swallow-size: -1