spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: 5MB

minio:
  access:
    name: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
  bucket:
    name: ${MINIO_BUCKET}
  url: http://${MINIO_HOST}:${MINIO_PORT}