spring:
  profiles:
    active: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4777/cloud_file_storage
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
